- id: web-application-small
  name: Web Application Checklist - Small
  categories:
    - password-reset-function
    - security-headers


- id: web-cms-wordpress
  name: Wordpress CMS
  categories:
    - wordpress-cms